name: simple-micro-auth-pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-test:
    runs-on: ubuntu-20.04
    environment: testing_env
    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: docker build .


  app-test:
    runs-on: ubuntu-20.04
    environment: testing_env
    services:
      postgres:
        image: postgres:15.3-alpine3.18
        env:
          POSTGRES_DB: postgres_db_github
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build
      run: go build ./src/main.go

    - name: Test
      run: go test ./src/tests
      env:
        GO_ENV=test
        DOCKERIZED=true
        TEST_DATABASE_HOST=127.0.0.1
        TEST_DATABASE_PORT=5432
        TEST_DATABASE_USER=postgres_user
        TEST_DATABASE_PASSWORD=postgres_password
        TEST_DATABASE_DBNAME=postgres_db
        TEST_DATABASE_SSLMODE=disable
        TEST_JWT_SECRET=${{ secrets.TEST_JWT_SECRET }}
        TEST_JWT_TTL=${{ vars.JWT_TTL }}
        PORT=${{ vars.PORT }}
